services:
  windows:
    image: dockurr/windows:latest
    container_name: windows11
    network_mode: bridge

    environment:
      VERSION: "win11"
      LANGUAGE: "Portuguese"
      REGION: "pt-BR"
      KEYBOARD: "pt-BR"
      NETWORK_MODE: "nat"

      RAM_SIZE: "8G"
      CPU_CORES: "4"
      DISK_SIZE: "64G"

      USERNAME: "Docker"
      PASSWORD: "admin"
      AUTOLOGIN: "Y"

    devices:
      - /dev/kvm
      - /dev/net/tun

    cap_add:
      - NET_ADMIN

    ports:
      - "8006:8006"
      - "3389:3389/tcp"
      - "3389:3389/udp"

    volumes:
      - windows_data:/storage

    restart: unless-stopped

volumes:
  windows_data:
